kind: Service
apiVersion: v1
metadata:
  name: whoamistudent2
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: whoamistudent2
